id: P010467
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:51:22.309168
source_metadata:
  id: bdr:W1KG18764
  title: དུས་གསུམ་ཕྱོགས་བསྒྲིགས་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    147a73be8f3d4ec3a9ec3b864e9ccfd6:
      image_group_id: I1KG20609
      title: ''
      volume_number: 1
      total_pages: 106
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
